import themeDataJson from "../theme-data.json";

/**
 * The generated theme tables (bases, accents, radii, fonts, densities…) as a JS module.
 *
 * Consumers must read them through this export rather than importing
 * `@kanzo-tech/theme/theme-data.json` directly. A raw JSON subpath import is an ESM JSON
 * import at runtime, which Node rejects without `with { type: "json" }` — and Rollup strips
 * that attribute when bundling, so there is no way to make the direct import survive a build.
 * Bundling the data into this package's own JS entry is safe: it is the package that owns the
 * data, so the copy can never skew from the CSS generated alongside it.
 */
export const themeData = themeDataJson;
export type ThemeData = typeof themeDataJson;

/**
 * The categorical-palette checks — the gate every scheme passes before it is registered.
 *
 * Exported from the domain because the rule and the data belong together: anything deriving a
 * scheme (from a named palette's hues, from a customer's ramps) needs the same verdict this
 * package's own tests apply, not a copy of it.
 */
export {
  BAND,
  CHROMA_FLOOR,
  CONTRAST_MIN,
  CVD_FLOOR,
  CVD_TARGET,
  NORMAL_FLOOR,
  SURFACE,
  TEXT_MIN,
  checkScheme,
  contrast as contrastRatio,
  deltaE,
  hueDistance,
  oklch,
  type CvdKind,
  type Mode,
  type PairList,
  type SchemeReport,
} from "./palette-check.js";

/**
 * The anti-corruption layer: a named palette contributes hues, the system's ramps contribute
 * lightness and chroma, and the checks decide. Measured, not assumed — no named palette tested so
 * far passes as a categorical scheme in its own values.
 */
export {
  allPairsCap,
  deriveScheme,
  familyOf,
  orderScheme,
  type Derivation,
  type OrderOptions,
} from "./derive-scheme.js";

/**
 * `@kanzo-tech/theme` — design tokens, the theme axis table, and the value types. No React.
 *
 * Theming is driven by `data-*` attributes on `<html>`, whose token values live in
 * `themes.css` (generated from Shark's exact colour/radius data):
 * · `data-base`       — the neutral scale (background/card/muted/border/…).
 * · `data-accent`     — overrides only the 6 primary/ring tokens.
 * · `data-radius`     — sets `--radius`.
 * · `data-font`       — sets `--font-sans`.
 * · `data-mono-font`  — sets `--font-mono`.
 * · `data-font-size`  — sets the root font-size (the rem density scale).
 *
 * Writing those attributes is `<KanzoThemeProvider>`'s job, from `@kanzo-tech/ui`. It sets them
 * on `document.documentElement` — see the AXES note below for why a wrapper element cannot work.
 *
 * Dark mode is not owned here: the host toggles `.dark` on `<html>` (next-themes or the
 * provider's built-in fallback) and the generated dark rules key off that ancestor.
 *
 * Requires `@kanzo-tech/ui/styles.css` (or the raw token/theme CSS) imported once at the root.
 */

/** Appearance PREFERENCE — light, dark, or `system` (follow the OS). */
export type Appearance = "light" | "dark" | "system";

/** The APPLIED appearance, after `system` is resolved against the OS. */
export type ResolvedAppearance = "light" | "dark";

/**
 * A colour identity by name — Kanzo, Dracula, Nord, Catppuccin.
 *
 * Open like the font and scheme axes, because a product ships its own. The shape a palette must
 * have is base16: sixteen slots with documented roles, which is the interchange format these
 * palettes already exist in and the mapping the 13 `--kanzo-syntax-*` roles were waiting for.
 */
export type KanzoPalette = "kanzo" | "kanzo-dark" | (string & {});

/** The sixteen base16 slots. `base00`–`base07` neutrals, `base08`–`base0F` accents. */
export type PaletteSlot =
  | "base00" | "base01" | "base02" | "base03" | "base04" | "base05" | "base06" | "base07"
  | "base08" | "base09" | "base0A" | "base0B" | "base0C" | "base0D" | "base0E" | "base0F";

export interface Palette {
  label: string;
  /**
   * The appearance this palette *is*, not one it can be put into.
   *
   * A palette carries `color-scheme`, so selecting a dark one darkens form controls and scrollbars
   * without a mode being chosen alongside it. This is the axis the light/dark toggle folds into.
   */
  appearance: ResolvedAppearance;
  /**
   * The partner palette of the same identity, or `null`.
   *
   * Pairing is what replaces the light/dark dichotomy, following daisyUI: `prefers-color-scheme`
   * selects the partner rather than inverting a mode, and the manual control becomes a palette
   * switcher. A palette with no partner — Dracula is dark-first and has no light side worth
   * inventing — simply pins the appearance while it is selected.
   */
  pairsWith: string | null;
  /** The sixteen slots. */
  slots: Record<PaletteSlot, string>;
  /**
   * Slots this package manufactured because the source palette does not document them.
   *
   * Almost no palette defines base06/base07 — Dracula names four greys where base16 wants eight —
   * so they are generated by carrying `base05` toward the ink extreme. No token reads them; they
   * exist for base16 completeness, and this field says which ones are not the palette's own word.
   */
  extended: PaletteSlot[];
  /**
   * Slots below `TEXT_MIN` on this palette's own `base00`.
   *
   * A property of the palette rather than of the mapping — Nord's comments are 1.7:1 in Nord, and
   * Catppuccin Latte is low-contrast by design. Unlike a scheme's `relief` there is no relief
   * channel to offer in exchange, because these render as text. Published so the choice is informed.
   */
  relief: PaletteSlot[];
  /** The tokens `[data-palette="…"]` sets — surfaces, the 13 syntax roles, and `color-scheme`. */
  vars: Record<string, string>;
}

/** Base neutral scale — the full set (surfaced only in the playground theme-editor). */
export type KanzoBase =
  | "slate" | "gray" | "zinc" | "neutral" | "stone" | "mauve" | "olive" | "mist" | "taupe";

/** Accent hues — the full set: `neutral` + the 17 Tailwind hues (playground editor). */
export type KanzoAccent =
  | "neutral" | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald"
  | "teal" | "cyan" | "sky" | "blue" | "indigo" | "violet" | "purple" | "fuchsia" | "pink" | "rose";

/** Curated accent subset surfaced in the product Preferences panel (keasy's names). */
export type CuratedAccent = "neutral" | "blue" | "green" | "violet" | "orange" | "rose";

/** Radius steps (`md` = 0.5rem default). */
export type KanzoRadius = "none" | "xs" | "sm" | "md" | "lg";

/** Density (root font-size rem-scale); `default` omits the attribute. */
export type KanzoDensity = "default" | "compact" | "comfortable";

/** Sans font key — host-extensible; the DS ships `system`/`geist`/`inter` stacks. */
export type KanzoFont = "system" | "geist" | "inter" | (string & {});

/** Mono font key — host-extensible; the DS ships `system`/`geist-mono`/`jetbrains-mono`. */
export type KanzoMonoFont = "system" | "geist-mono" | "jetbrains-mono" | (string & {});

/**
 * A categorical scheme by name — the colours that carry *identity* (which series, which node kind,
 * which chip), as opposed to `accent`, which is the one brand hue.
 *
 * Open like the font axes, because schemes are extensible: the reference for that is Vega's
 * `vega.scheme(name, colors)`, a two-argument registry rather than a plugin system. Here the
 * registration is `schemeColors` on the prefs, which overrides the named scheme the same way
 * `primary` overrides `accent` and `baseTint` overrides `base`.
 */
export type KanzoScheme = "kanzo" | (string & {});

/**
 * A scheme's slots, per mode. Both arrays are the same length, and dark is *selected* rather than
 * derived — an automatic flip of a light palette lands outside the dark lightness band.
 */
export interface SchemeColors {
  light: string[];
  dark: string[];
}

/** A built-in scheme: its slots, plus what a panel needs to name it and to warn honestly. */
export interface Scheme extends SchemeColors {
  label: string;
  /**
   * How many real categories this scheme can name.
   *
   * The arrays are always as long as there are `--chart-*` tokens; `slots` is the *capacity*. A
   * palette that yields six usable hue families produces a six-slot scheme whose last two entries
   * are the muted "Other" token — explicit, rather than left at the `:root` defaults where a
   * seventh series would silently borrow a colour from a different scheme.
   */
  slots: number;
  /**
   * Slots falling below 3:1 on that mode's surface.
   *
   * Not a failure — the contrast check is a documented conditional relax — but not dismissable
   * either: where this is non-zero the chart owes a relief channel, visible direct labels or the
   * table view. Surfaced so choosing a scheme is an informed choice rather than a pretty one.
   */
  relief: { light: number; dark: number };
}

// ── The axis table — the single source of truth for how a preference reaches the DOM ────────
//
// This lives here, not in @kanzo-tech/ui, because three separate things must agree on it and
// two of them are in different packages: the React provider, the SSR pre-hydration script, and
// `scripts/gen-theme.mjs`, which decides which selectors exist in themes.css at all. When they
// drifted there was no type error to catch it — miss the generator and the provider writes an
// attribute no CSS matches; miss the script and the FOUC it exists to prevent comes back.

export interface ThemePrefs {
  /**
   * The colour identity — surfaces, neutrals and the 13 syntax roles, plus `color-scheme`.
   *
   * It does not yet own `accent` or the status colours. base16 nominates no primary, so taking one
   * would be inventing brand from a syntax slot; and its red/yellow/green slots mean *strings* and
   * *classes*, so wiring them to destructive/warning/success would let a palette say "this
   * succeeded" in whatever hue it uses for literals. The chart scheme is derived rather than
   * mapped — see `deriveScheme`, and the measurement that made it necessary.
   */
  palette: KanzoPalette;
  /** Any of the full accent set; the product panel offers the curated subset. */
  accent: KanzoAccent;
  radius: KanzoRadius;
  font: KanzoFont;
  monoFont: KanzoMonoFont;
  density: KanzoDensity;
  /** Supported but not surfaced by the default panel — default neutral. */
  base?: KanzoBase;
  /** Custom primary colour (any CSS colour). When set it overrides the `accent` preset by
   *  writing `--primary`/`--ring`/`--sidebar-primary(-ring)` inline; foreground is derived. */
  primary?: string;
  /** Custom base TINT (any CSS colour). When set it generates a neutral ramp tinted toward this
   *  hue (`--color-custom-*` + `data-base="custom"`), overriding the named `base`. */
  baseTint?: string;
  /** The categorical scheme by name — `--chart-1..N`, the colours that carry series identity. */
  scheme?: KanzoScheme;
  /** A registered scheme's own slots. When set it overrides the named `scheme` by writing
   *  `--chart-*` inline, picking the array that matches the applied appearance. Unlike `primary`,
   *  this one is mode-aware: a categorical palette that clears the light lightness band will not
   *  clear the dark one, so both sides are given rather than derived. */
  schemeColors?: SchemeColors;
}

export const DEFAULT_PREFS: ThemePrefs = {
  palette: themeDataJson.defaultPalette,
  accent: "neutral",
  radius: "md",
  font: "system",
  monoFont: "system",
  density: "default",
  base: "neutral",
  scheme: themeDataJson.defaultScheme,
};

/** The built-in schemes by name. Extend at runtime with `schemeColors` — the registry. */
export const SCHEMES = themeDataJson.schemes as unknown as Record<string, Scheme>;

/** The built-in palettes by name, with their slots, their measured relief, and their pairing. */
export const PALETTES = themeDataJson.palettes as unknown as Record<string, Palette>;

/** `--chart-1` … `--chart-N` — the inline custom-scheme override, and what to clean up after it. */
export const CHART_SLOT_VARS: string[] = (SCHEMES[themeDataJson.defaultScheme] as Scheme).light.map(
  (_, i) => `--chart-${i + 1}`,
);

export const STORAGE_KEY = "kanzo_theme_prefs";
export const APPEARANCE_KEY = "kanzo_appearance";

/**
 * Each axis → its `<html>` attribute + default value (at the default the attribute is removed).
 *
 * These attributes go on `<html>`, never a wrapper element. Ark overlays (Dialog, Popover,
 * Menu, Select, Tooltip, Toast…) portal to `document.body`, outside any wrapper, so tokens set
 * on a wrapper would not reach them. `density` additionally *must* be on the root: it sets the
 * root font-size and every size in the system is `rem`.
 */
export const AXES: { key: keyof ThemePrefs; attr: string; def: string }[] = [
  // First, so its generated block is not the one that has to win a specificity tie it did not ask
  // for — precedence over `data-base` is settled in themes.css by source order, not here.
  { key: "palette", attr: "data-palette", def: themeDataJson.defaultPalette },
  { key: "base", attr: "data-base", def: "neutral" },
  { key: "accent", attr: "data-accent", def: "neutral" },
  // `data-chart-scheme`, not `data-scheme` — the latter reads as CSS `color-scheme`, and `.dark`
  // lives on this same element, so the ambiguity would be paid for daily.
  { key: "scheme", attr: "data-chart-scheme", def: themeDataJson.defaultScheme },
  { key: "radius", attr: "data-radius", def: "md" },
  { key: "font", attr: "data-font", def: "system" },
  { key: "monoFont", attr: "data-mono-font", def: "system" },
  { key: "density", attr: "data-font-size", def: "default" },
];

export const PRIMARY_OVERRIDE = ["--primary", "--ring", "--sidebar-primary", "--sidebar-ring"];
export const PRIMARY_FG_OVERRIDE = ["--primary-foreground", "--sidebar-primary-foreground"];
