/*
 * gen-theme.mjs — emits `packages/theme/themes.css` and `packages/theme/theme-data.json`.
 *
 * Two things: the catalogue of themes, read off `themes/*.css`, and the declaration of the user's
 * preferences — appearance, the theme worn on each side, and density. Nothing a theme owns is here:
 * radius, the faces and every other shape knob are authored in the theme, and a value with no
 * control cannot be overridden by one. See `/docs/design/preferences` for the rule.
 *
 * **Colour is not an axis** — see the header of `tokens.css`. A theme is `themes/<name>.css`,
 * hand-written source, and this file only enumerates the catalogue.
 *
 * Run: node packages/theme/scripts/gen-theme.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "themes.css");

// ── Density — `[value, css, label]`, authored once: the declaration, the panel and the docs table
//    all read this. Relative to the BROWSER's font size, never a pixel value: a person who set their
//    browser to 20px and picked compact gets 17.5px, not 14. `default` = attribute absent, which
//    leaves the browser's own size in place. ──
const DENSITIES = [["compact", "87.5%", "Compact"], ["comfortable", "112.5%", "Cozy"]];
const ALL_DENSITIES = [["default", "100%", "Default"], ...DENSITIES];

const block = (sel, vars) =>
  `${sel} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;

let out = `/* GENERATED by scripts/gen-theme.mjs. Do not edit by hand.
   Two things: the catalogue of themes, and the density preference layered over whatever theme
   is on. A theme is \`themes/<name>.css\` and is SOURCE — hand-written, one flat
   block. This file never contains a colour. */\n\n`;

// ── The catalogue ────────────────────────────────────────────────────────────
// Read from disk rather than listed, so adding a theme is adding a file. Each file names its family
// and label in its header (`@family`, `@label`): a family is a light theme and a dark one, and the
// pair is what a day/night picker offers. The family whose light theme binds the bare document comes
// first, so `themeIndex[0]` and its partner are the default pair.
const THEME_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "themes");
const THEMES = readdirSync(THEME_DIR)
  .filter((f) => f.endsWith(".css"))
  .map((file) => {
    const css = readFileSync(join(THEME_DIR, file), "utf8");
    const value = file.slice(0, -4);
    const family = /@family\s+([a-z0-9-]+)/.exec(css)?.[1];
    const label = /@label\s+(.+)/.exec(css)?.[1]?.trim();
    if (!family || !label) throw new Error(`themes/${file}: the header must name @family and @label`);
    const dark = /color-scheme:\s*dark\b/.test(css);
    const bare = css.replace(/\/\*[\s\S]*?\*\//g, "").includes(":root:not([data-theme])");
    return { file, value, label, dark, family, bare };
  });
const DEFAULT_FAMILY = THEMES.find((t) => t.bare && !t.dark)?.family;
THEMES.sort(
  (a, b) =>
    Number(b.family === DEFAULT_FAMILY) - Number(a.family === DEFAULT_FAMILY) ||
    a.family.localeCompare(b.family) ||
    Number(a.dark) - Number(b.dark),
);
for (const family of new Set(THEMES.map((t) => t.family))) {
  const sides = THEMES.filter((t) => t.family === family).map((t) => t.dark);
  if (sides.length !== 2 || sides[0] === sides[1])
    throw new Error(`family "${family}" needs exactly one light theme and one dark theme`);
}
out += THEMES.map((t) => `@import "./themes/${t.file}";`).join("\n") + "\n\n";

out += "/* ── Density (data-font-size → root font-size rem-scale) ────────────────── */\n";
for (const [d, size] of DENSITIES) out += block(`[data-font-size="${d}"]`, { "font-size": size });

writeFileSync(OUT, out);

// ── The declarations — one per core axis, in the shape a section contributes ─────────────────────
//
// `SectionPrefDecl` from `src/sections.ts`, plus `source`, which is core-only: it says WHO emits the
// selectors the attribute matches. `"themes"` is this file, so the drift guards in `index.test.ts`
// can hold the declaration against the sheet; `"document"` is `compile()`, from a document a TENANT
// authored after this package was built, and there is nothing here to check it against.
//
// The core does not import the type — a generator emitting a shape the package declares would be a
// build-order dependency for no gain — so the guard is `index.test.ts` reading this back through
// `CORE_PREFS`, and `check:generated`, which regenerates and fails on a diff.
//
// Three entries, because three things are the person's: which side, which theme on it, and how big
// everything is. `appearance` has no `attr`: it writes a class, not an attribute. It is in this
// table anyway because the table is what the panel draws from. While nothing is stored, its starting
// value is the OS's `prefers-color-scheme`; a stored choice wins.
const choice = (options, rest) => ({ kind: "choice", options, ...rest });
const corePrefs = () => ({
  appearance: choice(
    [
      { value: "light", label: "Light" },
      { value: "dark", label: "Dark" },
    ],
    { default: "light", label: "Appearance", doc: "which side of the document is worn" },
  ),
  density: choice(
    ALL_DENSITIES.map(([value, , label]) => ({ value, label })),
    {
      default: "default",
      attr: "data-font-size",
      source: "themes",
      personal: true,
      label: "Density",
      doc: "the root size everything scales from",
    },
  ),
  /**
   * The one whose options a CLIENT writes.
   *
   * `{ from: … }` rather than a list, because a value here is a theme somebody authored and no
   * generator can enumerate a tenant's. `default: ""` keeps a single-theme tenant's `<html>`
   * byte-identical: the write rule removes the attribute at the default.
   *
   * **This is `palette` + `identity` + `paletteByAppearance`, collapsed into one.** It had to be
   * three while a document was a two-mode stylesheet that a brand could be layered onto: the
   * document picked the colours, the identity picked which brand within it, and the map picked
   * which document each side wore. A theme is one mode and one flat block, so a brand is not a
   * layer over a document — it IS a theme — and choosing is choosing.
   *
   * `byAppearance` survives, and it is the whole of what `a-palette-is-chosen-per-appearance`
   * asked for. A tenant may ship themes that are each correct and still not equally wanted on both
   * sides, and the person who knows is the one watching the screen flip. The pre-hydration script
   * resolves appearance before it writes anything, so it can index the map — that ordering is what
   * makes the axis possible.
   *
   * `source: "document"`, even though this file now emits the catalogue. What it emits is a list of
   * `@import`s; the SELECTORS live in hand-written theme files, and their values are the tenant's.
   * That is the whole distinction the two guards below hold — a `"themes"` axis is one whose values
   * this package fixes at build time, and fixing a tenant's themes is the line the colour layer
   * exists to keep.
   */
  themeByAppearance: choice(
    { from: "themes" },
    {
      default: "",
      attr: "data-theme",
      source: "document",
      byAppearance: true,
      label: "Theme",
      doc: "which theme is worn on this side",
    },
  ),
});

// ── theme-data.json — the same data as a runtime module ──────────────────────
// Consumers read it through the package's JS entry, never this `.json` subpath — see `themeData` in
// `src/index.ts` for why the direct import cannot be made to survive a build.
const data = {
  densities: Object.fromEntries(ALL_DENSITIES.map(([d, v]) => [d, v])),
  // The catalogue, read off disk — so the panel lists what actually ships and no second list can
  // drift from it. `dark` is the theme's own `color-scheme`, which is what "one mode" means.
  themes: THEMES.map(({ value, label, dark, family }) => ({ value, label, dark, family })),
  prefs: corePrefs(),
  // What a token defers to when a theme stays quiet, read off `tokens.css` so nothing restates it.
  //
  // A theme authors about thirty declarations and the vocabulary is fifty-four; the difference is
  // this table. It ships because resolving a token is not something only CSS needs to do — an
  // authoring tool showing you what a theme *looks like* has to follow the same chain the cascade
  // follows, and the alternative was a second copy of it typed into the studio.
  fallbacks: (() => {
    const bridge = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "tokens.css"), "utf8");
    const chains = {};
    for (const [, body] of bridge.matchAll(/^\s*--color-[a-z0-9-]+:\s*(var\([^;]+);/gm)) {
      const [head, ...rest] = [...body.matchAll(/--[a-z0-9-]+/g)].map((m) => m[0]);
      if (head && rest.length) chains[head] = rest;
    }
    return chains;
  })(),
};
const JSON_OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "theme-data.json");
writeFileSync(JSON_OUT, JSON.stringify(data, null, 2));
