/*
 * gen-theme.mjs — emits `packages/theme/themes.css` and `packages/theme/theme-data.json`.
 *
 * MECHANISM: the four NON-COLOUR axes, and nothing else. Theming is driven by `data-*` attributes
 * on <html>: `data-radius` sets --radius, `data-font`/`data-mono-font` set the font stacks, and
 * `data-font-size` sets the density (root font-size). The default value of every axis = attribute
 * ABSENT, so a product only sets what it changes.
 *
 * **Colour is not an axis** — see the header of `tokens.css`, which carries that argument in full.
 * There is no colour here and no colour generator beside it: a theme is `themes/<name>.css`,
 * hand-written source, and this file only enumerates the catalogue.
 *
 * The tables the derivation READS moved out with it, to
 * (the derivation this used to sit beside is gone — a browser that
 * loads this package's `themeData` has no use for a single one of them.
 *
 * Run: node packages/theme/scripts/gen-theme.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "themes.css");

// Every table below is `[value, css, label]`. The label is here rather than in the panel because
// this file is the one place a value is authored: an option list typed beside the control is a
// hand-copy of this data, and `Preferences.tsx` held two of them — `RADII` and `DENSITIES` — sitting
// next to the generated tables they duplicated. Adding a font is one line here, and the panel, the
// declaration and the docs table follow.

// ── Radius (Shark's BORDER_RADIUS) ───────────────────────────────────────────
// The label IS the key, and deliberately: these are steps on a slider whose markers are the names
// people use for them ("md"), not prose. A "Medium" here would be a second word for one step.
// The value is the FIELD radius — a button, an input, a tab. The other two are derived from it by
// the ratios below rather than authored five more times: a preference is one step on one slider,
// and a user who wants a rounder card and a squarer button is asking for a THEME, not a preference.
// A theme declares all three independently, which is the capacity the single `--radius` never had.
const RADII = [
  ["none", "0rem", "none"],
  ["xs", "0.125rem", "xs"],
  ["sm", "0.25rem", "sm"],
  ["md", "0.5rem", "md"],
  ["lg", "0.625rem", "lg"],
];

/** box : field : selector. At `md` this is 0.75 / 0.5 / 0.25rem, which is what `tokens.css` falls
    back to — so the attribute-absent case and `data-radius="md"` agree by construction. */
const RADIUS_RATIO = { box: 1.5, field: 1, selector: 0.5 };

const rem = (base, mul) => `${Number((parseFloat(base) * mul).toFixed(4))}rem`;

// ── Fonts — the DS ships NO font files. `data-font`/`data-mono-font` point --font-sans/
//    --font-mono at a stack; `var(--font-*)` keys let a host inject its own webfont var
//    (e.g. next/font sets --font-geist-sans) with a graceful system fallback. ──
const SYSTEM_SANS = 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
const SYSTEM_MONO = 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace';
const FONTS = [
  ["system", SYSTEM_SANS, "System"],
  ["geist", `var(--font-geist-sans, ${SYSTEM_SANS})`, "Geist"],
  ["inter", `var(--font-inter, ${SYSTEM_SANS})`, "Inter"],
];
const MONO_FONTS = [
  ["system", SYSTEM_MONO, "System"],
  ["geist-mono", `var(--font-geist-mono, ${SYSTEM_MONO})`, "Geist Mono"],
  ["jetbrains-mono", `var(--font-jetbrains-mono, ${SYSTEM_MONO})`, "JetBrains"],
];

// ── Density (matches keasy's data-font-size → root font-size rem-scale). `default`
//    = attribute absent (16px). ──
const DENSITIES = [["compact", "14px", "Compact"], ["comfortable", "18px", "Cozy"]];
const ALL_DENSITIES = [["default", "16px", "Default"], ...DENSITIES];

const block = (sel, vars) =>
  `${sel} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;

let out = `/* GENERATED by scripts/gen-theme.mjs. Do not edit by hand.
   Two things: the catalogue of themes, and the user's non-colour preferences layered over
   whatever theme is on. A theme is \`themes/<name>.css\` and is SOURCE — hand-written, one flat
   block. This file never contains a colour. */\n\n`;

// ── The catalogue ────────────────────────────────────────────────────────────
// Read from disk rather than listed, so adding a theme is adding a file. A consumer who wants a
// subset imports the individual sheets instead of this one.
const THEMES = readdirSync(join(dirname(fileURLToPath(import.meta.url)), "..", "themes"))
  .filter((f) => f.endsWith(".css"))
  .sort();
out += THEMES.map((f) => `@import "./themes/${f}";`).join("\n") + "\n\n";

out += "/* ── Radius (data-radius) ───────────────────────────────────────────────── */\n";
for (const [r, val] of RADII)
  out += block(`[data-radius="${r}"]`, {
    "--radius-box": rem(val, RADIUS_RATIO.box),
    "--radius-field": rem(val, RADIUS_RATIO.field),
    "--radius-selector": rem(val, RADIUS_RATIO.selector),
  });

out += "\n/* ── Fonts (data-font / data-mono-font) ─────────────────────────────────── */\n";
// `--font-heading` moves with `--font-sans`, because there is ONE font axis. It used to be set
// nowhere at all, so `card.tsx`, `alert.tsx`, `dialog.tsx` and `Preferences.tsx` — every title in
// the library — sat on the `tokens.css` fallback while body text followed the preference. A
// product that wants a distinct display face still overrides `--font-heading` on its own, which is
// what `tokens.css` promises; a second axis is not something anything here has asked for.
for (const [f, stack] of FONTS)
  out += block(`[data-font="${f}"]`, { "--font-sans": stack, "--font-heading": stack });
for (const [f, stack] of MONO_FONTS) out += block(`[data-mono-font="${f}"]`, { "--font-mono": stack });

out += "\n/* ── Density (data-font-size → root font-size rem-scale) ────────────────── */\n";
for (const [d, size] of DENSITIES) out += block(`[data-font-size="${d}"]`, { "font-size": size });

writeFileSync(OUT, out);

// ── The declarations — one per core axis, in the shape a section contributes ─────────────────────
//
// `SectionPrefDecl` from `src/sections.ts`, plus `source`, which is core-only: it says WHO emits the
// selectors the attribute matches. `"themes"` is this file, so the drift guards in `index.test.ts`
// can hold the declaration against the sheet; `"document"` is `compile()`, from a document a TENANT
// authored after this package was built, and there is nothing here to check it against.
//
// The core does not import the type — a generator emitting a shape the package declares would be a
// build-order dependency for no gain — so the guard is `index.test.ts` reading this back through
// `CORE_PREFS`, and `check:generated`, which regenerates and fails on a diff.
//
// `appearance` is declared and has no `attr`: it writes a class, not an attribute. It is in this
// table anyway because the table is what the panel draws from, and appearance is a choice a user
// makes — with `""` as a listed option, which is the value that means *ask the OS*. It used to be
// reachable only through the panel's Reset button.
const choice = (options, rest) => ({ kind: "choice", options, ...rest });
const corePrefs = () => ({
  appearance: choice(
    [
      { value: "", label: "System" },
      { value: "light", label: "Light" },
      { value: "dark", label: "Dark" },
    ],
    { default: "", label: "Appearance", doc: "which side of the document is worn" },
  ),
  radius: choice(
    RADII.map(([value, , label]) => ({ value, label })),
    { default: "md", attr: "data-radius", source: "themes", label: "Radius", doc: "how round a corner is" },
  ),
  font: choice(
    FONTS.map(([value, , label]) => ({ value, label })),
    { default: "system", attr: "data-font", source: "themes", label: "Font", doc: "the face body text is set in" },
  ),
  monoFont: choice(
    MONO_FONTS.map(([value, , label]) => ({ value, label })),
    {
      default: "system",
      attr: "data-mono-font",
      source: "themes",
      label: "Mono font",
      doc: "the face code is set in",
    },
  ),
  density: choice(
    ALL_DENSITIES.map(([value, , label]) => ({ value, label })),
    {
      default: "default",
      attr: "data-font-size",
      source: "themes",
      label: "Density",
      doc: "the root size everything scales from",
    },
  ),
  /**
   * The one whose options a CLIENT writes.
   *
   * `{ from: … }` rather than a list, because a value here is a theme somebody authored and no
   * generator can enumerate a tenant's. `default: ""` keeps a single-theme tenant's `<html>`
   * byte-identical: the write rule removes the attribute at the default.
   *
   * **This is `palette` + `identity` + `paletteByAppearance`, collapsed into one.** It had to be
   * three while a document was a two-mode stylesheet that a brand could be layered onto: the
   * document picked the colours, the identity picked which brand within it, and the map picked
   * which document each side wore. A theme is one mode and one flat block, so a brand is not a
   * layer over a document — it IS a theme — and choosing is choosing.
   *
   * `byAppearance` survives, and it is the whole of what `a-palette-is-chosen-per-appearance`
   * asked for. A tenant may ship themes that are each correct and still not equally wanted on both
   * sides, and the person who knows is the one watching the screen flip. The pre-hydration script
   * resolves appearance before it writes anything, so it can index the map — that ordering is what
   * makes the axis possible.
   *
   * `source: "document"`, even though this file now emits the catalogue. What it emits is a list of
   * `@import`s; the SELECTORS live in hand-written theme files, and their values are the tenant's.
   * That is the whole distinction the two guards below hold — a `"themes"` axis is one whose values
   * this package fixes at build time, and fixing a tenant's themes is the line the colour layer
   * exists to keep.
   */
  themeByAppearance: choice(
    { from: "themes" },
    {
      default: "",
      attr: "data-theme",
      source: "document",
      byAppearance: true,
      label: "Theme",
      doc: "which theme is worn on this side",
    },
  ),
});

// ── theme-data.json — the same data as a runtime module ──────────────────────
// Consumers read it through the package's JS entry, never this `.json` subpath — see `themeData` in
// `src/index.ts` for why the direct import cannot be made to survive a build.
const data = {
  radii: Object.fromEntries(RADII.map(([r, v]) => [r, v])),
  fonts: Object.fromEntries(FONTS.map(([f, v]) => [f, v])),
  monoFonts: Object.fromEntries(MONO_FONTS.map(([f, v]) => [f, v])),
  densities: Object.fromEntries(ALL_DENSITIES.map(([d, v]) => [d, v])),
  // The catalogue, read off disk — so the panel lists what actually ships and no second list can
  // drift from it. `dark` is the theme's own `color-scheme`, which is what "one mode" means.
  themes: THEMES.map((f) => {
    const name = f.slice(0, -4);
    const css = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "themes", f), "utf8");
    return { name, dark: /color-scheme:\s*dark\b/.test(css) };
  }),
  prefs: corePrefs(),
  // What a token defers to when a theme stays quiet, read off `tokens.css` so nothing restates it.
  //
  // A theme authors about thirty declarations and the vocabulary is fifty-four; the difference is
  // this table. It ships because resolving a token is not something only CSS needs to do — an
  // authoring tool showing you what a theme *looks like* has to follow the same chain the cascade
  // follows, and the alternative was a second copy of it typed into the studio.
  fallbacks: (() => {
    const bridge = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "tokens.css"), "utf8");
    const chains = {};
    for (const [, body] of bridge.matchAll(/^\s*--color-[a-z0-9-]+:\s*(var\([^;]+);/gm)) {
      const [head, ...rest] = [...body.matchAll(/--[a-z0-9-]+/g)].map((m) => m[0]);
      if (head && rest.length) chains[head] = rest;
    }
    return chains;
  })(),
};
const JSON_OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "theme-data.json");
writeFileSync(JSON_OUT, JSON.stringify(data, null, 2));
